# theme: jekyll-theme-cayman
title: Smart Contract with Ethereum
description: Blockchain based automation for collecting rents and controlling physical access.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
